
reversed_dict_most={
'Counselor (Si)': ['Aarde, Economie en Duurzaamheid',
  'Ancient studies',
  'Communication Social Science',
  'Communication and Information Studies',
  'Cultural Anthropology and Development Sociology',
  'English Language and Communication Studies',
  'European Studies',
  'Interdisciplinaire sociale wetenschap',
  'Language Learning and Language Teaching',
  'Linguistics',
  'Literatuurwetenschap',
  'Media and Culture',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Onderwijswetenschappen',
  'Political Science',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',#done
  ],
 'Initiator (DI)': [
  'Aardewetenschappen',
  'Bedrijfskunde',
  'Ancient studies',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'European Studies',
  'Fiscaal recht',
  'Bedrijfskunde',
  'Business administration (bedrijfskunde)',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Duitse Taal en Cultuur',
  'Business administration (bedrijfskunde)',
  'Filosofie',
  'Notarieel Recht',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies'],#done

 'Encourager (Is)': [
  'Communication Social Science',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Rechtsgeleerdheid',
  'scheikunde',
  'tandheelkunde'
  'Bedrijfskunde',
  'Business administration (bedrijfskunde)',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'English Language and Communication Studies',#DONE
],
 'Analyst (C)': ['Aarde, Economie en Duurzaamheid',
  'Business Analytics',
  'Econometrics and Business economics',
  'Econometrie',
  'Economie en Bedrijfskunde',
  'Fiscale Economie',
  'Informatica',
  'Informatiekunde',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Business analytics',
  'Econometrics and Business economics',
  'Econometrie',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'Mechanical Engineering',#DONE
  ],
 'Harmonizer (IS)': ['Aardewetenschappen',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Archeologie',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Cognition, Language and Communication',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'scheikunde',
  'Sociology',
  'Cultuurwetenschappen',
  'Econometrie en Operationele Research', #DONE
],
 'Planner (Sc)': ['Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Artificial Intelligence',
  'Communication Social Science',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Economics and Business Economics','Scandinavië studies',
  'Sociale geografie en Planologie',
  'Econometrie',
  'Economics and Business Economics',
  'English Language and Communication Studies',
  'European Studies',
  'Future Planet Studies',
  'Geneeskunde', #DONE
],
 'Editor (Cs)': ['Actuariële Wetenschappen',
  'Artificial Intelligence',
  'Econometrics and Business economics',
  'Fiscaal recht',
  'Informatica',
  'Mechanical Engineering',
  'Media and Information',
  'Politicologie',
  'scheikunde',
  'tandheelkunde'
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde'],#DONE

 'Skeptic (Cd)': ['Actuariële Wetenschappen',
  'Business Analytics',
  'Econometrics and Business economics',
  'Informatica',
  'Informatiekunde',
  'Kunstmatige intelligentie',
  'Mechanical Engineering',
  'Theaterwetenschap',
  'Actuarial Science',
  'Political Science',
  'Economie en Bedrijfskunde',
  'English Language and Communication Studies',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Future Planet Studies',  
  'Rechtsgeleerdheid',
  'Scandinavië studies',], #DONE
 'Questioner (CD)': [
     'Economie en Bedrijfskunde',
  'Farmaceutische Wetenschappen',
  'Aarde, Economie en Duurzaamheid',
  'Actuariële Wetenschappen',
  'Arabische taal en cultuur',
  'Artificial Intelligence',
  'Business Analytics',
  'Fiscaal recht',
  'Fiscale Economie',
  'Global Arts, Culture and Politics',
  'History and International Studies',
  'Ancient studies',
  'Cognition, Language and Communication',
  'Cultuurwetenschappen',
  'Econometrie',
  'Geschiedenis',
  'Actuarial Science','Language and Media',
  'Law in Society','International Business Administration',
  'Literatuurwetenschap',], #done
 'Motivator (I)': ['Archeologie',
  'Bedrijfskunde',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Econometrics and Business economics',
  'History and International Studies',
  'Theaterwetenschap',
  'Communicatiewetenschap',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Duitse Taal en Cultuur',
  'Econometrie',
  'Farmaceutische Wetenschappen',  'scheikunde',
  'Griekse en Latijnse Taal en Cultuur', #10
 ],
 'Stabilizer (SC)': ['Artificial Intelligence',
  'Criminologie',
  'Econometrics and Business economics',
  'Filosofie',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Archeologie',
  'English Language and Communication Studies',
  'European Studies', 
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Cognition, Language and Communication',
  'Communication Social Science',
  'Communication and Information Studies',
  'Cultural anthropology and Development Sociology',
  'Geschiedenis',
  'Literature and Society',
  'Psychobiologie',
  'Sociale geografie en Planologie', 'Farmaceutische Wetenschappen',
  'Fiscaal recht',], #done
 'Driver (Di)': ['Bedrijfskunde',
  'Fiscaal recht',
  'Literatuurwetenschap',
  'Sociale geografie en Planologie','Griekse en Latijnse taal en cultuur',
  'Actuariële Wetenschappen',
  'Arabische taal en cultuur',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cultuurwetenschappen',
  'Econometrics and Business economics',
  'Econometrie',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'English Language and Communication Studies',
  'European Studies',
  'Filosofie',
  'International Business Administration',
  'Law in Society',
  'Media Art Design and Architecture'], #done
 'Architect (Dc)': ['Business Analytics',
  'Business administration (bedrijfskunde)',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde','International Business Administration',
  'Italie studies',
  'Law in Society',
  'Literature and Society',
  'Sociology',
  'Arabische taal en cultuur',
  'Criminologie',
  'English Language and Communication Studies',
  'Fiscaal recht',
  'Fiscale Economie',
  'Future Planet Studies',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse taal en cultuur',
  'History and International Studies',
  'Media en Journalistiek',
  'Cultuurwetenschappen', #done
  ],
 'Captain (D)': ['Business administration (bedrijfskunde)',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Hebreeuwse taal en cultuur',
  'Informatica',
  'Language and Media'
  'Arabische taal en cultuur',
  'Kunstmatige intelligentie',
  'Natuur- en sterrenkunde',
  'Notarieel Recht',
  'Political Science',
  'Politicologie',
  'Psychobiologie',
  'Scandinavië studies',
  'Actuarial Science'], #done
 'Supporter (S)': ['Cognition, Language and Communication',
  'Communication Social Science',
  'Criminologie',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Econometrics and Business economics',
  'Econometrie',  'Economie en Bedrijfskunde',
  'Cultural Anthropology and Development Sociology',
  'Economics and Business Economics',
  'European Studies',
  'Filosofie',
  'Future Planet Studies', 'tandheelkunde'
  'Geneeskunde', #10
],
 'Influencer (Id)': ['Communicatiewetenschap',
  'Criminologie',
  'Fiscale Economie',
  'Business administration (bedrijfskunde)',
  'Business analytics',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Geneeskunde',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies', #done
  ]}
reversed_dict_less={'Captain (D)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Ancient studies',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Econometrie',
  'Econometrie en Operationele Research',
  'Englisch language and Culture',
  'Archeologie',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Econometrics and Business economics',
  'Economie en Bedrijfskunde',
 #done
  ],
 'Initiator (DI)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Archeologie',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Business Analytics',
  'Cognition, Language and Communication',
  'Arabische taal en cultuur',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Duitslandstudies',
  'Econometrie',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'Fiscale Economie',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Medische informatiekunde',#done
],
 'Encourager (Is)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Ancient studies',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Cognition, Language and Communication',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Econometrics and Business economics',
  'Econometrie',
  'Arabische taal en cultuur',
  'Archeologie',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
#20
  ],
 'Motivator (I)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Ancient studies',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'communicatiewetenschap',
  'tandheelkunde'
  'Arabische taal en cultuur',
  'Archeologie',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Econometrics and Business economics',
  'History and International Studies',
  'Theaterwetenschap',
  ], #done
 'Influencer (Id)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Arabische taal en cultuur',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Ancient studies',
  'Archeologie',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Econometrie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Business Analytics',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Econometrics and Business economics','tandheelkunde' #done
  ],
 'Harmonizer (IS)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Ancient studies',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Econometrie',
  'Englisch language and Culture',
  'Actuarial Science','Duitse Taal en Cultuur',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Economie en Bedrijfskunde',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Arabische taal en cultuur',
  'Archeologie',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'scheikunde',  'Sociology',
  'Cultuurwetenschappen', #done
  ],
 'Questioner (CD)': [
  'Business administration (bedrijfskunde)',
  'Communication Social Science',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Filosofie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Communicatiewetenschap',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Informatica',
  'Informatiekunde',
  'Mechanical Engineering' 'Notarieel Recht',
  'Political Science',
 ], #done
 'Planner (Sc)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Arabische taal en cultuur',
  'Archeologie',
  'Actuarial Science',
  'Ancient studies',
  'Scandinavië studies',
  'Bedrijfskunde',
  'Tandheelkunde',
  'Politicologie',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Fiscaal recht',
  'Fiscale Economie',
  'Business Analytics',
 #done
 ],
 'Stabilizer (SC)': ['Aarde, Economie en Duurzaamheid',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'Informatica',
  'Informatiekunde',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Duitse Taal en Cultuur',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
 #done
  ],
 'Counselor (Si)': [
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Archeologie',
  'Geneeskunde',
  'Geschiedenis',
  'History and International Studies',
  'Informatiekunde',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Criminologie',
  'Cultural anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Econometrics and Business economics',
  'Econometrie',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Scandinavië studies',#done
  ],
 'Skeptic (Cd)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Ancient studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Econometrie',
  'Englisch language and Culture',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Franse taal en cultuur',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'Artificial Intelligence',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Cultural anthropology and Development Sociology',
  'Econometrics and Business economics',
  'Econometrie en Operationele Research',
  'Economics and Business Economics', #20
  
  ],
 'Supporter (S)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Archeologie',
  'Rechtsgeleerdheid',
  'Sociale geografie en Planologie',
  'Actuarial Science',  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Italie studies',
  'Linguistics',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Scandinavië studies',
  'Scheikunde',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
  'Media and Culture',
  'Media and Information',
  'Media Art Design and Architecture',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Communication Social Science',
  'Communication and Information Studies',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  
  'scheikunde', #20
  ],
 'Driver (Di)': ['Aarde, Economie en Duurzaamheid',
  'Fiscaal recht',
  'Fiscale Economie',
  'Gezondheidswetenschappen',
  'Sociology',
  'Archeologie',
  'Artificial Intelligence',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Taalwetenschap',
  'Tandheelkunde',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'
  'Griekse en Latijnse Taal en Cultuur','Literature and Society', #done
 ],
 'Editor (Cs)': ['Aarde, Economie en Duurzaamheid',
  'Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Archeologie',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Culturele antropologie en ontwikkelingssociologie',
  'Cultuurwetenschappen',
  'Farmaceutische Wetenschappen',
  'Fiscale Economie' , 'Theaterwetenschap', #20
  
],
 'Architect (Dc)': ['Aarde, Economie en Duurzaamheid',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Cultural Anthropology and Development Sociology',
  'Cultural anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Culturele antropologie en ontwikkelingssociologie',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Econometrics and Business economics',
  'Econometrie',
  'Englisch language and Culture',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Franse taal en cultuur',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Hebreeuwse taal en cultuur',
  'Bedrijfskunde',
  'Business Analytics',
  'Business administration (bedrijfskunde)',

  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',

  'Informatiekunde', 'Medische informatiekunde',   #20
  ],
 'Analyst (C)': ['Aardewetenschappen',
  'Actuariële Wetenschappen',
  'Archeologie',
'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Scheikunde',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Tandheelkunde',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'Cognition, Language and Communication',
  'Criminologie',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie', #20
]}

reversed_dict_least={'Counselor (Si)': [
  'Actuarial Science',
  'Bedrijfskunde',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Business Analytics',
  'Business administration (bedrijfskunde)',
  'Business analytics',
  'Cognition, Language and Communication',
  
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
  'scheikunde',
  'tandheelkunde'],
 'Initiator (DI)': ['Actuarial Science',
  'Ancient studies',
  'Artificial Intelligence',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Farmaceutische Wetenschappen',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'
  ],
 'Encourager (Is)': [
   'Actuarial Science',
  'Actuariële Wetenschappen',
  'Economie en Bedrijfskunde',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Scheikunde',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
],
 'Analyst (C)': ['Actuarial Science',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Natuur- en sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'tandheelkunde'],
 'Harmonizer (IS)': ['Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Computational Social Science (Data- en sociale wetenschap)',
  
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Scheikunde',
  'Sociale geografie en Planologie',
  'Taalwetenschap',
  'Theaterwetenschap',
  'tandheelkunde'],
 'Planner (Sc)': [
  'Bestuurs- en organistatiewetenschap',
  'Communicatiewetenschap',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Economie en Bedrijfskunde',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Bewegingswetenschap',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Sociology',
  'Taalwetenschap',

  'Theaterwetenschap',],
 'Editor (Cs)': ['Actuarial Science',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Econometrie',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Filosofie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Scheikunde',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Tandheelkunde',
  'communicatiewetenschap'],
 'Skeptic (Cd)': ['Arabische taal en cultuur',
  'Archeologie',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Cognition, Language and Communication',
  'Communicatiewetenschap',
  'Communication Social Science',
  'Communication and Information Studies',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'],
 'Questioner (CD)': ['Aardewetenschappen',
  'Actuarial Science',
  'Archeologie',
  'Bedrijfskunde',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Geneeskunde',
  'Gezondheidswetenschappen',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'Interdisciplinaire sociale wetenschap',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Linguistics',
  'Literature and Society',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Tandheelkunde',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde'],
 'Motivator (I)': [
 'Actuarial Science',
  'Communication and Information Studies',
  'Criminologie',

  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Cultural Anthropology and Development Sociology',
  'Cultuurwetenschappen',
  'Duitse Taal en Cultuur',
  'Econometrie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatica',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
],
 'Stabilizer (SC)': ['Actuarial Science',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Bestuurs- en organistatiewetenschap',
  
  'Bewegingswetenschap',
  'Business administration (bedrijfskunde)',
  'Communicatiewetenschap',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Cultuurwetenschappen',
  'Duitslandstudies',
  'Econometrie',
  'Englisch language and Culture',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'],
 'Driver (Di)': ['Aardewetenschappen',
  'Actuarial Science',
  'Ancient studies',
  'Communication and Information Studies',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Criminologie',
  'Cultural Anthropology and Development Sociology',
  'Culturele antropologie en ontwikkelingssociologie',
  'Duitse Taal en Cultuur',
  'Duitslandstudies',
  'Englisch language and Culture',
  'Farmaceutische Wetenschappen',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Global Arts, Culture and Politics',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
],
 'Architect (Dc)': ['Aardewetenschappen',
  'Actuarial Science',
  'Actuariële Wetenschappen',
  'Ancient studies',
  'Archeologie',
  'Artificial Intelligence',
  'Informatica',
  'Interdisciplinaire sociale wetenschap',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Linguistics',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media Art Design and Architecture',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Psychobiologie',
  'Rechtsgeleerdheid',
  'Scandinavië studies',
  'Sociale geografie en Planologie',
  'Taalwetenschap',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'],
 'Captain (D)': ['Actuariële Wetenschappen',
  'Arabische taal en cultuur',
  'Archeologie',
  'Artificial Intelligence',
    'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Geschiedenis',
  'Griekse en Latijnse Taal en Cultuur',
  'History and International Studies',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Italie studies',
  'Language Learning and Language Teaching',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Nederlandse taal en cultuur',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Politics, Psychology, Law and Economics (PPLE)',
  'Rechtsgeleerdheid',
  'Sociale geografie en Planologie',
  'Taalwetenschap',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde',
  'tandheelkunde'
  ],
 'Supporter (S)': ['Actuariële Wetenschappen',
  'Ancient studies',
  'Arabische taal en cultuur',
  'Bestuurs- en organistatiewetenschap',
  'Bewegingswetenschap',
  'Computational Social Science (Data- en sociale wetenschap)',
  'Culturele antropologie en Ontwikkelingssociolgie',
  'Duitslandstudies',
  'Englisch language and Culture',
  'Franse taal en cultuur',
  'Informatica',
  'Interdisciplinaire sociale wetenschap',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Medische informatiekunde',

  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'History and International Studies',
  'Informatiekunde',
  'International Business Administration',
  'Italie studies',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Media and Culture',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',

 ],
 'Influencer (Id)': [
  'Actuarial Science',
  'Econometrie en Operationele Research',
  'Economics and Business Economics',
  'Economie en Bedrijfskunde',
  'Englisch language and Culture',
  'English Language and Communication Studies',
  'European Studies',
  'Farmaceutische Wetenschappen',
  'Filosofie',
  'Fiscaal recht',
  'Fiscale Economie',
  'Franse taal en cultuur',
  'Future Planet Studies',
  'Geneeskunde',
  'Geschiedenis',
  'Gezondheidswetenschappen',
  'Global Arts, Culture and Politics',
  'Griekse en Latijnse Taal en Cultuur',
  'Hebreeuwse taal en cultuur',
  'Informatiekunde',
  'Interdisciplinaire sociale wetenschap',
  'International Business Administration',
  'Kunstmatige intelligentie',
  'Language Learning and Language Teaching',
  'Language and Media',
  'Law in Society',
  'Linguistics',
  'Literature and Society',
  'Literatuurwetenschap',
  'Mechanical Engineering',
  'Media and Culture',
  'Media and Information',
  'Media en Journalistiek',
  'Media Art Design and Architecture',
  'Medische informatiekunde',
  'Natuur- en Sterrenkunde',
  'Nederlandse taal en cultuur',
  'Notarieel Recht',
  'Onderwijswetenschappen',
  'Oudheidwetenschappen',
  'Pedagogische wetenschappen',
  'Political Science',
  'Politicologie',
  'Sociale geografie en Planologie',
  'Sociology',
  'Taalwetenschap',
  'Theaterwetenschap',
  'communicatiewetenschap',
  'scheikunde'
]}

natural_sciences=[
'Aarde, Economie en Duurzaamheid',
'Aardewetenschappen',
'Future Planet Studies',
'Geneeskunde',
'Natuur- en Sterrenkunde'
'Scheikunde']

social_sciences=['Actuariële Wetenschappen',
 'Bedrijfskunde',
 'Business administration (bedrijfskunde)',
 'Business Analytics',
 'Communication Social Science',
 'Communicatiewetenschap',
 'Criminologie',
 'Econometrics and Business economics',
 'Econometrie',
 'Econometrie en Operationele Research',
 'Economics and Business Economics',
 'Economie en Bedrijfskunde',
 'European Studies',
 'Farmaceutische Wetenschappen',
 'Fiscaal recht',
 'Fiscale Economie',
 'Geschiedenis',
 'Gezondheidswetenschappen',
 'Global Arts, Culture and Politics',
 'Interdisciplinaire sociale wetenschap',
 'International Business Administration',
 'Linguistics',
 'Literature and Society',
 'Literatuurwetenschap',
 'Media and Culture',
 'Media and Information',
 'Media en Journalistiek',
 'Media Art Design and Architecture',
 'Medische informatiekunde',
 'Nederlandse taal en cultuur',
 'Notarieel Recht',
 'Onderwijswetenschappen',
 'Pedagogische wetenschappen',
 'Political Science',
 'Politicologie',
 'Politics, Psychology, Law and Economics (PPLE)',
 'Scandinavië studies',
 'Sociale geografie en Planologie',
 'Sociology',
 'Taalwetenschap',
 'Theaterwetenschap']

engineering_and_technology=['Artificial Intelligence',
 'Informatica',
 'Informatiekunde',
 'Italie studies',
 'Mechanical Engineering',
 'Tandheelkunde']

humanities=['Ancient studies',
 'Archeologie',
 'Cultuurwetenschappen',
 'Duitse Taal en Cultuur',
 'Duitslandstudies',
 'Englisch language and Culture',
 'English Language and Communication Studies',
 'Filosofie',
 'Franse taal en cultuur',
 'Griekse en Latijnse Taal en Cultuur',
 'Hebreeuwse taal en cultuur',
 'History and International Studies',
 'Language Learning and Language Teaching',
 'Language and Media',
 'Law in Society',
 'Literatuurwetenschap',
 'Oudheidwetenschappen',
 'Oudheidwetenschappen',
 'Theaterwetenschap']